name: lALALAL
favicon: null
layout_spectrum: 0.5137542416341603
typography_spectrum: 0.9353083760943264
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9301145058125257
  lightness: 0.9687050646170974
  saturation: 0.3916029704269022
  rhythmicContrast: 0.00544978235848248
purpose: []
